version: "3"
services:
 proxy:
  image : nginx
  container_name: proxy
  ports:
    - 80:80
  depends_on:
    - frontend
  volumes:
    - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
  restart: always

 frontend:
  build: ./frontend
  image: frontend
  container_name: frontend
  restart: always


